from django.urls import path
from .views import (ProductListCreateView, 
                    ProductDetailView, 
                    CartView, 
                    AddToCartView, 
                    RemoveFromCartView, 
                    UpdateCartItemView, 
                    ClearCartView, 
                    CreateOrderView, 
                    OrderListView, 
                    OrderDetailView, 
                    OrderListView, 
                    OrderDetailView,
                    UpdateOrderStatusView)

urlpatterns = [
    path('', ProductListCreateView.as_view(), name='product-list-create'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('cart/', CartView.as_view(), name='cart-detail'),
    path('cart/add/', AddToCartView.as_view(), name='cart-add'),
    path('cart/remove/', RemoveFromCartView.as_view(), name='cart-remove'),
    path('cart/update/', UpdateCartItemView.as_view()),
    path('cart/clear/', ClearCartView.as_view()),
    path('orders/create/', CreateOrderView.as_view()),
    path('orders/', OrderListView.as_view()),
    path('orders/<int:pk>/', OrderDetailView.as_view()),
    path('orders/', OrderListView.as_view(), name='order-list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('orders/<int:pk>/status/', UpdateOrderStatusView.as_view()),
]
